spring.application.name=transaction-gateway-api
server.port=8081
server.shutdown=graceful

transaction.service.url=${TRANSACTION_SERVICE_URL:http://localhost:8082}
app.aes.key-base64=${APP_AES_KEY_BASE64}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

security.jwt.secret-base64=${SECURITY_JWT_SECRET_BASE64}
security.jwt.issuer=${SECURITY_JWT_ISSUER:reto-developer-local}
security.jwt.audience=${SECURITY_JWT_AUDIENCE:transaction-api}

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
spring.mvc.log-resolved-exception=false

spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.client.config.transaction-service.connect-timeout=2000
spring.cloud.openfeign.client.config.transaction-service.read-timeout=5000

# Hardening HTTP
spring.mvc.problemdetails.enabled=true
spring.servlet.multipart.enabled=false
server.max-http-request-header-size=16KB
